site_name: TwinCAT XBox Controller Service Documentation

theme:
    name: material
    logo: Images/Controller.svg
    custom_dir: docs/overrides
    font:
        text: Arial
    features:
        - navigation.tabs
    # 404 page
    static_templates:
        - 404.html

extra_css:
    - style.css

use_directory_urls: false

repo_name: TC XBox Project GitHub
repo_url: https://github.com/Beckhoff-USA-Community/TwinCAT-XBox-Controller-Service
edit_uri: ""

markdown_extensions:
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight:
        linenums: true
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets

nav:
    - Home: index.md
    - Getting Started:
        - Introduction:             GettingStarted/Introduction.md
        - System Requirements:      GettingStarted/SystemRequirements.md
        - Installation:             GettingStarted/Installation.md
        - First Program:            GettingStarted/FirstProgram.md
        - API References:           APIReference/Overview.md
    - API References:
        - Overview:                 APIReference/Overview.md
        - Primary Function Blocks:
            - XBox Controller:      APIReference/XBoxController.md
        - Helper Function Blocks:
            - NC Axis Helpers:      APIReference/NCAxisHelper.md
            - XPlanar Helpers:      APIReference/XPlanarHelper.md
